/**
 * Unified Auth Context.
 * Supports both wallet (Solana) and email+password authentication.
 * Provides a single playerId for use throughout the app.
 */

import React, { createContext, useContext, useState, useCallback, useEffect } from 'react';
import { useSocket } from '../socket/SocketContext';
import { useWallet } from '../solana/WalletContext';

interface AuthResult {
  success: boolean;
  error?: string;
}

interface AuthContextType {
  playerId: string | null;
  username: string | null;
  authType: 'wallet' | 'email' | null;
  isAuthenticated: boolean;
  isLoading: boolean;
  loginWithEmail: (email: string, password: string) => Promise<AuthResult>;
  registerWithEmail: (email: string, password: string) => Promise<AuthResult>;
  connectWallet: () => Promise<void>;
  setUsername: (username: string) => Promise<AuthResult>;
  logout: () => void;
}

const AuthContext = createContext<AuthContextType | undefined>(undefined);

const TOKEN_KEY = 'batak_auth_token';

export const AuthProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const { socket, isConnected } = useSocket();
  const { publicKey, connected: walletConnected, connect: walletConnect, disconnect: walletDisconnect } = useWallet();

  const [playerId, setPlayerId] = useState<string | null>(null);
  const [username, setUsernameState] = useState<string | null>(null);
  const [authType, setAuthType] = useState<'wallet' | 'email' | null>(null);
  const [isLoading, setIsLoading] = useState(true);

  const isAuthenticated = !!playerId;

  // Auto-login: try stored token on socket connect
  useEffect(() => {
    if (!socket || !isConnected) {
      setIsLoading(true);
      return;
    }

    const storedToken = localStorage.getItem(TOKEN_KEY);
    if (storedToken) {
      socket.emit('auth_validate', { token: storedToken }, (response: any) => {
        if (response.success) {
          setPlayerId(response.playerId);
          setAuthType(response.authType);
          setUsernameState(response.username || null);
        } else {
          localStorage.removeItem(TOKEN_KEY);
        }
        setIsLoading(false);
      });
    } else {
      setIsLoading(false);
    }
  }, [socket, isConnected]);

  // When wallet connects, auto-generate wallet token
  useEffect(() => {
    if (!socket || !isConnected || !walletConnected || !publicKey) return;
    // Only generate wallet token if not already authenticated
    if (playerId) return;

    socket.emit('auth_wallet', { publicKey: publicKey.toString() }, (response: any) => {
      if (response.success && response.token) {
        localStorage.setItem(TOKEN_KEY, response.token);
        setPlayerId(response.playerId);
        setAuthType('wallet');
        setUsernameState(response.username || null);
      }
    });
  }, [socket, isConnected, walletConnected, publicKey, playerId]);

  const loginWithEmail = useCallback(async (email: string, password: string): Promise<AuthResult> => {
    if (!socket) return { success: false, error: 'Baglanti yok' };

    return new Promise((resolve) => {
      socket.emit('auth_login', { email, password }, (response: any) => {
        if (response.success && response.token) {
          localStorage.setItem(TOKEN_KEY, response.token);
          setPlayerId(response.playerId);
          setAuthType('email');
          setUsernameState(response.username || null);
          resolve({ success: true });
        } else {
          resolve({ success: false, error: response.error || 'Giris basarisiz' });
        }
      });
    });
  }, [socket]);

  const registerWithEmail = useCallback(async (email: string, password: string): Promise<AuthResult> => {
    if (!socket) return { success: false, error: 'Baglanti yok' };

    return new Promise((resolve) => {
      socket.emit('auth_register', { email, password }, (response: any) => {
        if (response.success && response.token) {
          localStorage.setItem(TOKEN_KEY, response.token);
          setPlayerId(response.playerId);
          setAuthType('email');
          setUsernameState(response.username || null);
          resolve({ success: true });
        } else {
          resolve({ success: false, error: response.error || 'Kayit basarisiz' });
        }
      });
    });
  }, [socket]);

  const connectWallet = useCallback(async () => {
    await walletConnect();
    // Wallet token will be generated by the useEffect above
  }, [walletConnect]);

  const setUsername = useCallback(async (name: string): Promise<AuthResult> => {
    if (!socket || !playerId) return { success: false, error: 'Baglanti yok' };

    return new Promise((resolve) => {
      socket.emit('set_username', { publicKey: playerId, username: name }, (response: any) => {
        if (response.success) {
          setUsernameState(response.username);
          resolve({ success: true });
        } else {
          resolve({ success: false, error: response.error || 'Kullanici adi kaydedilemedi' });
        }
      });
    });
  }, [socket, playerId]);

  const logout = useCallback(() => {
    localStorage.removeItem(TOKEN_KEY);
    setPlayerId(null);
    setUsernameState(null);
    setAuthType(null);
    // Disconnect wallet if it was a wallet auth
    if (authType === 'wallet') {
      walletDisconnect();
    }
  }, [authType, walletDisconnect]);

  const value: AuthContextType = {
    playerId,
    username,
    authType,
    isAuthenticated,
    isLoading,
    loginWithEmail,
    registerWithEmail,
    connectWallet,
    setUsername,
    logout,
  };

  return (
    <AuthContext.Provider value={value}>
      {children}
    </AuthContext.Provider>
  );
};

export const useAuth = (): AuthContextType => {
  const context = useContext(AuthContext);
  if (!context) {
    throw new Error('useAuth must be used within AuthProvider');
  }
  return context;
};
